- id: doi:10.1016/j.psychres.2024.116107
  type: paper
  description: Genetic determinants of coping, resilience and self-esteem in schizophrenia suggest a primary role for social factors and hippocampal neurogenesis.
  date: 2024-11
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0165178124003925-gr2.jpg
